### ISSUE TITLE
How to use/install?

### ISSUE THREAD

**Issue by 1x2x3x4x** [digaus/community-capacitor-wifi#11]
Thanks for this,

Sorry for the question, but how can I install this in a ionic/angular project? 
I've alrady added capacitor core to it, but I don't know how to get this.

**Comment by digaus** [comment]
Hello,

this repo is currently still WIP. I have not published it yet. You should however be able to `run npm install https://github.com/digaus/community-capacitor-wifi`.

Otherwise clone the repo and run `npm run build` and `npm run build-electron`. Then in your project you need to run `npm install {folder of wifi plugin}`

**Comment by 1x2x3x4x** [comment]
Thank you for the quick reply!
Would be better to try then your capacitor-wifi plugin for now?

**Comment by digaus** [comment]
> Thank you for the quick reply!
> Would be better to try then your capacitor-wifi plugin for now?

This one also supports electron, which my old plugin does not. I also did some refactoring and improvements. I would go with this plugin.

**Comment by 1x2x3x4x** [comment]
Alright, I'll try it out. 
One more question though.

I'm not sure how to include this in Android and iOS, how can I register it in the MainActivity.java? 
I'm following this example with no luck: https://devdactic.com/build-capacitor-plugin/

**Comment by digaus** [comment]
> Alright, I'll try it out.
> One more question though.
> 
> I'm not sure how to include this in Android and iOS, how can I register it in the MainActivity.java?
> I'm following this example with no luck: https://devdactic.com/build-capacitor-plugin/

You can follow the instructions in the link from "Android Plugin Integration". iOS should work out of the box.

**Comment by 1x2x3x4x** [comment]
Yes, but what would be the import for your package? In the example is: ` import com.devdactic.contacts.ContactsPlugin;`
The same for the` add()`, he uses `add(ContactsPlugin.class);`. for yours it'll be `add(WifiPlugin.class);` ?

**Comment by 1x2x3x4x** [comment]
I've finally managed to do it, I've edited the previous answer, thanks for your patience.

After finding my AP and tapping connect, I get a message at the bottom saying I was successfully connected but the pop-up with the name if the AP comes back up right away.

**Comment by digaus** [comment]
> I've finally managed to do it, I've edited the previous answer, thanks for your patience.
> 
> After finding my AP and tapping connect, I get a message at the bottom saying I was successfully connected but the pop-up with the name of the AP comes back up right away. The AP itself has no internet, since it's an IoT device. On the phone, under Settings/wifi, I see the messgeobtaining IP through blabla, but after a split seconds it gets disconnected. and then the pop-up comes back up.
> 
> **edit:** this is exactly what happens https://www.youtube.com/watch?v=U6ZGo5QMpew&feature=youtu.be&ab_channel=Vojt%C4%9BchBo%C4%8Dek
> 
> https://issuetracker.google.com/issues/158344328

Thats the issue which `forceWifiUsage` should have fixed. Will need to look into this out closer.

**Comment by digaus** [comment]
@1x2x3x4x 

Just made a PR: https://github.com/digaus/community-capacitor-wifi/pull/12
Can you try new master?

**Comment by 1x2x3x4x** [comment]
I don't think it's your code's fault. 
It seems OnePlus (OxygenOS) is bugged for some devices. I've only tried this on a OnePlus 5T but tommorow will try on a Samsung. 

https://forums.oneplus.com/threads/can-not-connect-to-a-hotspot-with-wifinetworkspecifier.1180889/

https://forums.oneplus.com/threads/wifinetworkspecifier-immediately-drops-connection.1219734/


Will update and let you know.

**Comment by digaus** [comment]
ok, I removed some NetworkCapabilities aswell.

**Comment by 1x2x3x4x** [comment]
Hi again, @digaus 

I tested the latest PR on these devices:

**Samsung S10 - Android 10**
> Connect: YES
> Disconnect: NO
> getIP: YES
> getSSID: YES


**OnePlus 5T - Android 10 [OxygenOS 10.0.0]**
> Connect: YES but it automatically disconnects (most likely their fault)
> Disconnect: NO
> getIP: YES
> getSSID: YES

**Xiaomi Redmi Note 8T- Android 9 [MIUI Global 11.0.9]**
> Connect: NO
> Disconnect: NO
> getIP: YES
> getSSID: YES

**Comment by 1x2x3x4x** [comment]
> Edit: Just tested on Samsung S10e with latest master. It stays connected to the network :)

It also disconnects?

**Comment by WolfWalter** [comment]
Hi,
I have the same Issue with my Oneplus 6T. Also reported the issue in https://forums.oneplus.com/threads/wifinetworkspecifier-immediately-drops-connection.1219734/

In the comments of a Blog post about Android NetworkStatsManager and Connectivity manager other Oneplus users are complaining about the issue: https://blog.ostebaronen.dk/2019/11/android-10-wifi.html

Also testet on a Pixel 3 XL with Android 10 and Android 11 with no issues.

**Comment by digaus** [comment]
Thanks for the feedback guys. I did not test 'disconnect' yet.

@1x2x3x4x 
On Android 10, disconnecting should only work on a network which you connected to via the app. 

Android 9 is currently completely untested because I only have Android 10+ devices.

**Comment by 1x2x3x4x** [comment]
Anytime. Do you have any ETA or plans for it? Also, is there any way I can help?


BTW, do you thnk it would be possible to add a function to retrieve the frequecy of the current wifi? Many IoT devices can only connect to 2.4Ghz frequency networks so knowing that before hand could be useful [eg. tell the user to conenct to a 2.4 network]. Let me know if you want me to start a new Issue to request this - if possible at all.

**Comment by digaus** [comment]
> Anytime. I'll test more devices and soon iOS.
> 
> Do you have any ETA or plans for it? Also, is there any way I can help?
> 
> BTW, do you thnk it would be possible to add a function to retrieve the frequecy of the current wifi? Many IoT devices can only connect to 2.4Ghz frequency networks so knowing that before hand could be useful [eg. tell the user to conenct to a 2.4 network]. Let me know if you want me to start a new issue to request this - if possible at all.

So I tested the disconnect function on Samsung S10e and it works just fine. It however only works when you have connected to the network via the app.

Same could be implemented for iOS.

For Android <10 you could try to clone my repo and make changes to get it to work. What error is thrown there when trying to connect?

Returning Frequency should be possible but currently is not the priority. I have to get all functions to work for my own IOT app :) so I will keep working on it for now.

**Comment by WolfWalter** [comment]
Just tested on a Samsung Galaxy S7 edge with Android 8. Connect and disconnect works, but the first time I try to connect only the Permission dialog for location is shown. I have to trigger connect again to establish the connection.

**Comment by kstearns** [comment]
Any working sample apps we could use as a starting point ?
So far I'm unable to get any API calls to work on any Android 9 or iOS 13 devices i have - any getters just return null and connect request silently fail .... not sure where to go from here.

Any help would be much appreciated.

**Comment by digaus** [comment]
> Any working sample apps we could use as a starting point ?
> So far I'm unable to get any API calls to work on any Android 9 or iOS 13 devices i have - any getters just return null and connect request silently fail .... not sure where to go from here.
> 
> Any help would be much appreciated.

```
import { WifiPlugin } from '@capacitor-community/wifi';
const Wifi: WifiPlugin = Plugins.Wifi as WifiPlugin;

[...]

 public async connectPrefix(ssid: string, password: string): Promise<void> {
        state.loading = true;
        this.state$.next(state);
        await Wifi.connectPrefix({ ssid, password })
                  .then((res: {ssid: string}) => state.ssid = res.ssid)
                  .catch((err: any) => state.error = err.toString());
        state.loading = false;
        this.state$.next(state);
    }

    public async connect(ssid: string, password: string): Promise<void> {
        state.loading = true;
        this.state$.next(state);
        await Wifi.connect({ ssid, password })
                  .then((res: {ssid: string}) => state.ssid = res.ssid)
                  .catch((err: any) => state.error = err.toString());
        state.loading = false;
        this.state$.next(state);
    }

    public async disconnect(): Promise<void> {
        state.loading = true;
        this.state$.next(state);
        await Wifi.disconnect()
                  .catch((err: any) => state.error = err.toString());
        state.loading = false;
        this.state$.next(state);
    }

    public async getSSID(): Promise<void> {
        state.loading = true;
        this.state$.next(state);
        await Wifi.getSSID()
                  .then((res: {ssid: string}) => state.ssid = res.ssid)
                  .catch((err: any) => state.error = err.toString());
        state.loading = false;
        this.state$.next(state);
    }

    public async getIP(): Promise<void> {
        state.loading = true;
        this.state$.next(state);
        await Wifi.getIP()
                  .then((res: {ip: string}) => state.ip = res.ip)
                  .catch((err: any) => state.error = err.toString());
        state.loading = false;
        this.state$.next(state);
    }
```

**Comment by kstearns** [comment]
Thanks, but that's basically what I already have setup in my Angular app (the script part is the easy part). What I'm suspecting to be the problem is really the Capacitor project/build and the resulting native Android/iOS projects - seems like I must be missing some native project details to make things work (or there are more version-specific bugs). I guess I was hoping to find a complete working Capacitor project that I could build and run (successfully) and then "diff" against my project to find the culprit.

**Comment by digaus** [comment]
> Thanks, but that's basically what I already have setup in my Angular app (the script part is the easy part). What I'm suspecting to be the problem is really the Capacitor project/build and the resulting native Android/iOS projects - seems like I must be missing some native project details to make things work (or there are more version-specific bugs). I guess I was hoping to find a complete working Capacitor project that I could build and run (successfully) and then "diff" against my project to find the culprit. Note that I have gone thru and added any permissions/entitlements I could find that I thought might be relevant, or that Google revealed might be required for that type of Wifi mgmt on Android/iOS devices.

Have you tried this? At least android should work there
https://github.com/digaus/capacitor-shellyhome

**Comment by kstearns** [comment]
Thanks. I haven't seen that app - I'll give it a try and let you know what I find.

**Comment by kstearns** [comment]
Ok, so the capacitor-shellyhome sample was helpful - that is fully functional on my Android 9 device, so it should help me isolate any differences in my Angular app/build. Also, when running on iOS, I'm at least able to query for IP and SSID. Any connect() and connectPrefix() requests in iOS still fail in the same way as my own app - iOS prompts user to connect to the network, but then the connect fails (and iOS prompts with the failure) without any useful debug info showing up in the console. Console debug is here:
APP ACTIVE
⚡️  To Native ->  Wifi connectPrefix 134123259
APP INACTIVE
APP ACTIVE
⚡️  TO JS {"ssid":"linksys"}
APP INACTIVE
APP ACTIVE

**Comment by kstearns** [comment]
Following up on my last comment with new information ... on iOS it does indeed add the new Wifi configuration, but it fails to connect. If I try to join from the "shelly" app, it fails, but if I go into iOS Wifi settings and select the network, it shows as an existing Wifi config (presents the "Forget network" option) and when I select it, it immediately joins (using the password provided from my app). So the Wifi config is definitely getting added, but fails to connect. I really have no idea where to go from - seems more like an iOS bug than anything else. I tried with joinOnce as true or false and didn't make a difference. Has anyone had any success on *any* version of iOS ?

**Comment by WolfWalter** [comment]
Today I tired the Plugin in iOS. At first it did not work. But after adding the needed capabilities in Xcode as documented in https://github.com/tripflex/WifiWizard2#ios-functions I was able to connect. To add the needed capabilities you have to be in the paid apple developer program. 

Disconnect is not yet implemented for iOS...

**Comment by digaus** [comment]
> Today I tired the Plugin in iOS. At first it did not work. But after adding the needed capabilities in Xcode as documented in https://github.com/tripflex/WifiWizard2#ios-functions I was able to connect. To add the needed capabilities you have to be in the paid apple developer program.
> 
> Disconnect is not yet implemented for iOS...

Thanks for the test. Yeah forgot about that. Once I finish my app I will update this plugin.

**Comment by sultanmyrza** [comment]
Hello want to contribute to make a full readme for developers with no native (ios, android) experience.
So far I was using https://ionicframework.com/docs/native/wifi-wizard-2 to connect to WiFi.
Which worked well on 

- ✅  iOS 
- ❌  Android (could't make it work) for `Android 10 (API level 29)`, `Android 11 (API level 30)` related [issue](https://github.com/tripflex/WifiWizard2/issues/99#issuecomment-669190932) 
> I just encountered that the connection functionality depends on the target SDK version set for the app. As soon as I increased the compile and target SKD version from 28 to 29 (as formally required by the play store since August 2020) (dis)connect did no longer work. Reverted to SDK 28 and it was fine again, even on devices with Android 10.

**_so now I want to describe detailed steps on installing https://github.com/digaus/community-capacitor-wifi plugin and try if it works on iOS and Android. I hope it will be usefull for web devs without much knowledge of native ios, android development_**

## Init project 
I have ionic + angular + capasitor project (should work same for React, Vue)
I'm following official [tutorial](https://ionicframework.com/docs/angular/your-first-app) to create project `ionic start photo-gallery tabs --type=angular --capacitor`

## installing community-capacitor-wifi
1. `npm install https://github.com/digaus/community-capacitor-wifi`
2.  `ionic build` (not sure though should I do this or not)?
3. `ionic cap sync` (not sure though should I do this or not)?
**after ionic cap sync make sure `@capacitor-community/wifi@0.0.1` plugin found both by iOS & Android**
    <details>
      <summary>ionic cap sync (click to expand)</summary>
      
      ```
      > capacitor sync
      [capacitor] ✔ Copying web assets from www to android/app/src/main/assets/public in 1.04s
      [capacitor] ✔ Creating capacitor.config.json in android/app/src/main/assets in 3.31ms
      [capacitor] [info] Found 3 Cordova plugins for android:
      [capacitor]        cordova-plugin-bluetoothle@6.6.1
      [capacitor]        cordova-plugin-wifiwizard2@3.1.1
      [capacitor]        es6-promise-plugin@4.2.2
      [capacitor] ✔ copy android in 1.14s
      [capacitor] ✔ Updating Android plugins in 15.58ms
      [capacitor] [info] Found 10 Capacitor plugins for android:
      [capacitor]        @capacitor-community/bluetooth-le@1.1.3
      [capacitor]        @capacitor-community/http@1.2.0
      [capacitor]        @capacitor-community/wifi@0.0.1
      [capacitor]        @capacitor/app@1.0.2
      [capacitor]        @capacitor/camera@1.0.3
      [capacitor]        @capacitor/filesystem@1.0.2
      [capacitor]        @capacitor/haptics@1.0.2
      [capacitor]        @capacitor/keyboard@1.0.2
      [capacitor]        @capacitor/status-bar@1.0.2
      [capacitor]        @capacitor/storage@1.0.3
      [capacitor] [info] Found 3 Cordova plugins for android:
      [capacitor]        cordova-plugin-bluetoothle@6.6.1
      [capacitor]        cordova-plugin-wifiwizard2@3.1.1
      [capacitor]        es6-promise-plugin@4.2.2
      [capacitor] ✔ update android in 82.54ms
      [capacitor] ✔ Copying web assets from www to ios/App/App/public in 1.11s
      [capacitor] ✔ Creating capacitor.config.json in ios/App/App in 814.67μp
      [capacitor] [info] Found 3 Cordova plugins for ios:
      [capacitor]        cordova-plugin-bluetoothle@6.6.1
      [capacitor]        cordova-plugin-wifiwizard2@3.1.1
      [capacitor]        es6-promise-plugin@4.2.2
      [capacitor] ✔ copy ios in 1.13s
      [capacitor] ✔ Updating iOS plugins in 10.58ms
      [capacitor] [info] Found 10 Capacitor plugins for ios:
      [capacitor]        @capacitor-community/bluetooth-le@1.1.3
      [capacitor]        @capacitor-community/http@1.2.0
      [capacitor]        @capacitor-community/wifi@0.0.1
      [capacitor]        @capacitor/app@1.0.2
      [capacitor]        @capacitor/camera@1.0.3
      [capacitor]        @capacitor/filesystem@1.0.2
      [capacitor]        @capacitor/haptics@1.0.2
      [capacitor]        @capacitor/keyboard@1.0.2
      [capacitor]        @capacitor/status-bar@1.0.2
      [capacitor]        @capacitor/storage@1.0.3
      [capacitor] [info] Found 3 Cordova plugins for ios:
      [capacitor]        cordova-plugin-bluetoothle@6.6.1
      [capacitor]        cordova-plugin-wifiwizard2@3.1.1
      [capacitor]        es6-promise-plugin@4.2.2
      [capacitor] ✔ Updating iOS native dependencies with pod install in 3.75s
      [capacitor] ✔ update ios in 3.79s
      [capacitor] ✔ copy web in 304.37μp
      [capacitor] ✔ update web in 366.60μp
      [capacitor] [info] Sync finished in 6.143s
      ```
    </details> 




## installing community-capacitor-wifi (android part)
1. <details>
      <summary>add permissions in AndroidManifest.xml (click to expand) </summary>
      
      ```xml
          <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
          <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
          <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
          <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
          <uses-permission android:name="android.permission.WRITE_SETTINGS" />
          <uses-permission android:name="android.permission.INTERNET" />
      ```
    </details>
2. <details>
      <summary>register the plugin in the `MainActivity.java` class (click to expand)</summary>
      
      ```java
          import com.digaus.capacitor.wifi.Wifi;
          
          [...]
          
            this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
                  // Additional plugins you've installed go here
                  // Ex: add(TotallyAwesomePlugin.class);
                  add(Wifi.class);
              }});
      ```
    </details>

## installing community-capacitor-wifi (ios part) 
1. <details> 
    <summary>add permissions in `App.entitlements` (click to expand) </summary>

      Read this first?
      https://betterprogramming.pub/wifi-permission-changes-for-ios-12-1-iphone-x-and-other-devices-c313e24f90ae

     finally add these in `App.entitlements`   
    ```xml
    <dict>
	    <key>com.apple.developer.networking.HotspotConfiguration</key>
	    <true/>
	    <key>com.apple.developer.networking.networkextension</key>
	    <array>
		    <string>app-proxy-provider</string>
	    </array>
	    <key>com.apple.external-accessory.wireless-configuration</key>
	    <true/>
	    <key>com.apple.developer.networking.wifi-info</key>
	    <true/>
    </dict>
    ```
</details>

TODO:
- [ ] add angular code snippet

will be updating as I proceed further

**Comment by sultanmyrza** [comment]
@digaus when I try to register the plugin in the `MainActivity.java` I got this 
![Screen Shot 2021-08-18 at 5 14 45 PM](https://user-images.githubusercontent.com/12681781/129873668-8054d28a-3dd8-440d-a6d3-a068375493c7.png)

Any ideas why? I have no native android development experience so would appreciate any help from anybody.

**Comment by sultanmyrza** [comment]
> @digaus when I try to register the plugin in the `MainActivity.java` I got this
> ![Screen Shot 2021-08-18 at 5 14 45 PM](https://user-images.githubusercontent.com/12681781/129873668-8054d28a-3dd8-440d-a6d3-a068375493c7.png)
> 
> Any ideas why? I have no native android development experience so would appreciate any help from anybody.

Okay if someone getting `Cannot resolve symbol 'digaus'`
just open android project and run command **Sync Project with Gradle Files** 
![Screen Shot 2021-08-18 at 5 32 02 PM](https://user-images.githubusercontent.com/12681781/129874730-cec257cd-e6a5-4a3d-9dbc-8ca475aa8845.png)

**Comment by digaus** [comment]
https://github.com/digaus/capacitor-plugin-demo

Added a demo app here :)

**Comment by 1x2x3x4x** [comment]
Hi, @digaus 

When doing npm install https://github.com/digaus/capacitor-plugin-demo 
I get this error:

> npm ERR! Could not install from "..\..\node_modules\community-capacitor-file-server" as it does not contain a package.json file.


Any idea why or how can I fix it? I want to try your new version of the plugin.

**Comment by digaus** [comment]
For now you also have to clone the plugins and run `npm run build` on them.

Then `npm run install` that folder

**Comment by 1x2x3x4x** [comment]
Ok, I'm following these steps:

1. `git clone https://github.com/digaus/capacitor-plugin-demo`
2. `git clone -b capacitor3 https://github.com/digaus/community-capacitor-wifi`
3. `npm run build `
> but this step fails with ` Cannot find module '@capacitor-community/wifi' or its corresponding type declarations.`

**Comment by digaus** [comment]
Have you checked out the correct branch?

**Comment by 1x2x3x4x** [comment]
Yes, capacitor3 is the branch you have created and also I've tried running the command in the demo folder you've also created. 
I'm not sure what I'm missing at this point.

**Comment by sultanmyrza** [comment]
> Ok, I'm following these steps:
> 
> 1. `git clone https://github.com/digaus/capacitor-plugin-demo`
> 2. `git clone -b capacitor3 https://github.com/digaus/community-capacitor-wifi`
> 3. `npm run build `
> 
> > but this step fails with ` Cannot find module '@capacitor-community/wifi' or its corresponding type declarations.`

@1x2x3x4x finally I understand real cause for the error 
```
Cannot find module '@capacitor-community/wifi' or its corresponding type declarations.
```
if plugin is not installed from npm but directly from git repo then you should add `"prepare": "npm run build"` in **package.json**, explained more at https://github.com/digaus/community-capacitor-wifi/issues/31#issuecomment-1045727188

**Comment by digaus** [comment]
https://github.com/digaus/community-capacitor-wifi/issues/37
