### ISSUE TITLE
Error when compiling iOS version

### ISSUE THREAD

**Issue by WolfWalter** [digaus/community-capacitor-wifi#16]
There is a unneeded "+" on this line:
https://github.com/digaus/community-capacitor-wifi/blob/07a2810e7caeb06e06962c005c2ede9df86fa6bf/ios/Plugin/Plugin.swift#L31

Bad merge?

**Comment by digaus** [comment]
@WolfWalter 
thanks for the info. Have not found time yet to test on iOS.

Can you check if https://github.com/digaus/community-capacitor-wifi/pull/17 fixes it?

**Comment by WolfWalter** [comment]
I already confirmed that by removing the "+" in in node_modules before. But I can only confirm that it builds. I am not able to test iOS at the moment.

**Comment by digaus** [comment]
OK Will close it for now :)
