### ISSUE TITLE
Updating plugin for capasitor 3.0

### ISSUE THREAD

**Issue by sultanmyrza** [digaus/community-capacitor-wifi#23]
any plans to update fro capasitor 3.0?
https://capacitorjs.com/docs/updating/plugins/3-0

**Comment by digaus** [comment]
Yes. Maybe I manage it later this day :)

**Comment by digaus** [comment]
@sultanmyrza 
You could try https://github.com/digaus/community-capacitor-wifi/tree/capacitor3

**Comment by sultanmyrza** [comment]
### How can I install it I tried 3 options but got errors

`npm install https://github.com/digaus/community-capacitor-wifi/tree/capacitor3`
```
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/digaus/community-capacitor-wifi/tree/capacitor3.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2021-08-19T02_13_11_496Z-debug.log
```
`npm install https://github.com/digaus/community-capacitor-wifi/tree/capacitor3 --save`
```
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/digaus/community-capacitor-wifi/tree/capacitor3.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2021-08-19T02_17_56_463Z-debug.log
```
`npm install git+https://github.com/digaus/community-capacitor-wifi/tree/capacitor3 --save`
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/digaus/community-capacitor-wifi/tree/capacitor3
npm ERR! 
npm ERR! fatal: repository 'https://github.com/digaus/community-capacitor-wifi/tree/capacitor3/' not found
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2021-08-19T02_18_15_317Z-debug.log
```

**Comment by sultanmyrza** [comment]
> ### How can I install it I tried 3 options but got errors
> `npm install https://github.com/digaus/community-capacitor-wifi/tree/capacitor3`
> 
> ```
> npm ERR! code ENOPACKAGEJSON
> npm ERR! package.json Non-registry package missing package.json: https://github.com/digaus/community-capacitor-wifi/tree/capacitor3.
> npm ERR! package.json npm can't find a package.json file in your current directory.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/*****/.npm/_logs/2021-08-19T02_13_11_496Z-debug.log
> ```
> 
> `npm install https://github.com/digaus/community-capacitor-wifi/tree/capacitor3 --save`
> 
> ```
> npm ERR! code ENOPACKAGEJSON
> npm ERR! package.json Non-registry package missing package.json: https://github.com/digaus/community-capacitor-wifi/tree/capacitor3.
> npm ERR! package.json npm can't find a package.json file in your current directory.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/*****/.npm/_logs/2021-08-19T02_17_56_463Z-debug.log
> ```
> 
> `npm install git+https://github.com/digaus/community-capacitor-wifi/tree/capacitor3 --save`
> 
> ```
> npm ERR! Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t https://github.com/digaus/community-capacitor-wifi/tree/capacitor3
> npm ERR! 
> npm ERR! fatal: repository 'https://github.com/digaus/community-capacitor-wifi/tree/capacitor3/' not found
> npm ERR! 
> npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/*****/.npm/_logs/2021-08-19T02_18_15_317Z-debug.log
> ```

### Solved
sorry my bead to install from branch ( https://github.com/digaus/community-capacitor-wifi/tree/capacitor3) I need to run 
`npm i https://github.com/digaus/community-capacitor-wifi.git#capacitor3`

**Comment by sultanmyrza** [comment]
## for android it starts seraching but can not find [Android 11 (API level 30)]
![Screenshot_20210819-113606_Settings](https://user-images.githubusercontent.com/12681781/130004020-007b1e38-bfc8-4182-b668-400b31102395.jpeg)
![Screenshot_20210819-113634_Settings](https://user-images.githubusercontent.com/12681781/130004041-fa5ff27e-316e-4665-9350-f36abc877b68.jpeg)
 
## for ios I got this error while compiling [iOS 14.6, xcode 12.3 (12C33)]
**ios error probably related to [this](https://github.com/capacitor-community/fcm/issues/70#issue-902803873)**
![Screen Shot 2021-08-19 at 11 34 31 AM](https://user-images.githubusercontent.com/12681781/130003597-fc26889f-39d6-4027-a47b-c67f84aefdb8.png)

**Comment by digaus** [comment]
What are you using for trying to connect to the GoPro?

Did not check iOS yet :)

**Comment by sultanmyrza** [comment]
### Tried `connectPrefix` on `android 11`
```json
{
   "save":false,
   "callbackId":"3802370",
   "pluginId":"Wifi",
   "methodName":"connectPrefix",
   "success":false,
   "error":{
      "message":"ERROR_CONNECT_FAILED_TIMEOUT"
   }
}
```

### Tried `connectPrefix` on `iOS 14.6`
{
   "errorMessage":"ERROR_CONNECTION_FAILED",
   "message":"ERROR_CONNECTION_FAILED"
}

**Comment by sultanmyrza** [comment]
> What are you using for trying to connect to the GoPro? `connect` or `connectPrefix` and with what value?
> 
> Did some changes to iOS now but did not test yet. You could give it a try.
### Yes compiled on xcode successfully

### Tried `connectPrefix` on `android 11`
```json
{
   "save":false,
   "callbackId":"3802370",
   "pluginId":"Wifi",
   "methodName":"connectPrefix",
   "success":false,
   "error":{
      "message":"ERROR_CONNECT_FAILED_TIMEOUT"
   }
}
```

### Tried `connectPrefix` on `iOS 14.6`
{
   "errorMessage":"ERROR_CONNECTION_FAILED",
   "message":"ERROR_CONNECTION_FAILED"
}
permissions for android and ios are granted aka App.entitlements etc.
originally I got WiFi connection working with WiFiWizzard but it was not working on android 

So I have no issues with permission on iOS and Android.
Tomorrow I will try to create fresh project and try again.

**Comment by digaus** [comment]
How does your prefix look like?

**Comment by digaus** [comment]
@sultanmyrza 

I just tried it on my Samsung S10e and it is working fine:
![Screenshot_20210819-204716_Settings](https://user-images.githubusercontent.com/15358538/130127335-e3b06371-3efe-445d-bb92-6515f0e1f48d.jpg)

**Comment by sultanmyrza** [comment]
> @sultanmyrza
> 
> I just tried it on my Samsung S10e and it is working fine. I tried `connect` and `connectPrefix`.
> 
> Please make sure that you supply the password when you want to connect to a secure network or otherwise leave it empty if the network is unsecured.
> 
> ![Screenshot_20210819-204716_Settings](https://user-images.githubusercontent.com/15358538/130127335-e3b06371-3efe-445d-bb92-6515f0e1f48d.jpg)

@digaus maybe I have wrong AndroidManifest file etc. Let me try your working demo https://github.com/digaus/capacitor-plugin-demo 

By the way thank you for the demo
I will test both on android and ios today 

And post a feedback here 🤗

**Comment by sultanmyrza** [comment]
@digaus In your example you depend on
```
"@capacitor-community/file-server": "git+https://github.com/digaus/community-capacitor-file-server.git#capacitor3",
"@capacitor-community/wifi": "git+https://github.com/digaus/community-capacitor-wifi.git#capacitor3",
```

is `"@capacitor-community/file-server": "git+https://github.com/digaus/community-capacitor-file-server.git#capacitor3"` necessary plugin to make WiFi work?

By the way what that plugin does?😅

**Comment by sultanmyrza** [comment]
> Samsung S10e

1. What is your android version `9.0` or `10.0`? Because I'm testing on `Android 11` and maybe need extra steps for `Android 11`?
2. And I'm also connecting to GoPro device throuth WiFi (is that change the situation)?
3. I'm not sure is connecting to regular wifi and gopro's wifi same thing?

**Comment by sultanmyrza** [comment]
> > Samsung S10e
> 
> 1. What is your android version `9.0` or `10.0`? Because I'm testing on `Android 11` and maybe need extra steps for `Android 11`?
> 2. And I'm also connecting to GoPro device throuth WiFi (is that change the situation)?
> 3. I'm not sure is connecting to regular wifi and gopro's wifi same thing?

Tested https://github.com/digaus/capacitor-plugin-demo on `Android 11` both Wifi.connect and WiFi.connectPrefix works ✅

But when I try to connect to my GoPro WiFi Access Point it can not connect (device not found) before I used WiFiWizzard2 to connect to go pro form iPhone but it was not working on android.

Why connecting to WiFi is not same as connecting to GoPro's WiFi Access Point? Probably I should ask this question [here](https://github.com/gopro/OpenGoPro/discussions) though.

By the way if instead of GoPro we have Raspery Pi with WiFi Access Point.
Can we connect to Raspery Pi's WiFi using this plugin? Just thinking aloud.

Have no idea why can not connect to GoPro's wifi access point

But for regular WiFi https://github.com/digaus/community-capacitor-wifi works fine (test on android for now)

**Comment by digaus** [comment]
@sultanmyrza 
I am also running on Android 11. It works nicely with Shelly IoT devices. Maybe the SSID you get from GoPro does not match with the real SSID of the GoPro? Have you verfied it by checking it in the Wifi settings what the SSID of the GoPro is?

**Comment by sultanmyrza** [comment]
> Edit: Maybe the SSID is hidden? Then we would need to add setIsHiddenSsid to the WifiNetworkSpecifier.Builder

Maybe 🤔 because when I scan from settings it's not shown. Probably I need tot try `setIsHiddenSsid` 

Is `WifiNetworkSpecifier.Builder` something that's is already implemented in this plugin or ...?

**Comment by digaus** [comment]
> > Edit: Maybe the SSID is hidden? Then we would need to add setIsHiddenSsid to the WifiNetworkSpecifier.Builder
> 
> Maybe 🤔 because when I scan from settings it's not shown. Probably I need tot try `setIsHiddenSsid`
> 
> Is `WifiNetworkSpecifier.Builder` something that's is already implemented in this plugin or ...?

Added the option `isHiddenSsid` to the `connect` function. Also updated demo project.

Hope this will work for you :)

**Comment by sultanmyrza** [comment]
> My iot devices do not have an internet connection. So I don't know why your GoPro is not working. Have you tried the `isHiddenSsid` parameter?

Yep I tried connect with isHiddenSsid, connectPrefix.
But on android even official GoPro App can not connect to its wifi but ios works fine.

I will tweka around and feedback soon.

**Comment by sultanmyrza** [comment]
@digaus finally resolved the issue was that 
GoPro WiFi Access Point has 2 options

- 2.4GHz (my iPhone can connect, my Android can connect)
- 5GHz (my iPhone can connect)

so in go pro setting I switched to 2.4 GHz and both iPhone and Android can connect to wifi using your plugin 🤗

>just side note here is how to know programmatically if android device support [5GHz](https://developer.android.com/reference/android/net/wifi/WifiManager#is5GHzBandSupported()) or [2.4GHz](https://developer.android.com/reference/android/net/wifi/WifiManager#is24GHzBandSupported())

**Comment by sultanmyrza** [comment]
I think I got false positive 

I think the reason wifi was able to connect because I use other app to connect to GoPro's wifi with official app 

Now when I reset go pro connection, unpair bluetooth and forget wifi and try to connect again it's can't connect/find wifi even if I pass hidden = true

**Comment by sultanmyrza** [comment]
I think I got false positive 

I think the reason wifi was able to connect because I use other app to connect to GoPro's wifi with official app 

Now when I reset go pro connection, unpair bluetooth and forget wifi and try to connect again it's can't connect/find wifi even if I pass hidden = true

**Comment by 1x2x3x4x** [comment]
Hi, 

I did: `npm i https://github.com/digaus/community-capacitor-wifi.git#capacitor3`
But now when I try to import the `Wifi` from `@capacitor-community/wifi `I get the error:

>  Cannot find module '@capacitor-community/wifi' or its corresponding type declarations.ts

**Comment by sultanmyrza** [comment]
> Hi,
> 
> I did: `npm i https://github.com/digaus/community-capacitor-wifi.git#capacitor3`
> But now when I try to import the `Wifi` from `@capacitor-community/wifi` I get the error:
> 
> > Cannot find module '@capacitor-community/wifi' or its corresponding type declarations.ts
> 
> But the files are there.

@1x2x3x4x happened to me as well I forgot how I resolved by basically 
try to 

delete `node_modules` and run `npm i`
reload your vscode 

or create fresh project and try to install to see if error goes away

**Comment by 1x2x3x4x** [comment]
I did both things and did not work, I must be missing something or you did something different. Your dependecies look like this?

>   "dependencies": {
    "@angular/common": "^12.0.1",
    "@angular/core": "^12.0.1",
    "@angular/forms": "^12.0.1",
    "@angular/platform-browser": "^12.0.1",
    "@angular/platform-browser-dynamic": "^12.0.1",
    "@angular/router": "^12.0.1",
    "@capacitor-community/wifi": "git+https://github.com/digaus/community-capacitor-wifi.git#capacitor3",
    "@capacitor/android": "^3.0.0",
    "@capacitor/camera": "^1.0.0",
    "@capacitor/core": "^3.0.0",
    "@capacitor/filesystem": "^1.0.0",
    "@capacitor/ios": "^3.0.0",
    "@capacitor/splash-screen": "^1.0.0",
    "@capacitor/storage": "^1.0.0",
    "@ionic/angular": "^5.6.7",
    "@ionic/pwa-elements": "^3.0.2",
    "core-js": "^3.6.5",
    "rxjs": "^6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  }


I'm interested specifically in the `@capacitor-community/wifi` line.

**Comment by sultanmyrza** [comment]
@1x2x3x4x did you resolve your problem?
yes here is my dependencies

```json
"dependencies": {
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@capacitor-community/wifi": "git+https://github.com/sultanmyrza/community-capacitor-wifi.git#capacitor3",
    "@capacitor/android": "3.2.2",
    "@capacitor/app": "1.0.3",
    "@capacitor/core": "3.2.2",
    "@capacitor/haptics": "1.0.3",
    "@capacitor/ios": "3.2.2",
    "@capacitor/keyboard": "1.0.3",
    "@capacitor/status-bar": "1.0.3",
    "@ionic/angular": "^5.5.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
```

**Comment by 1x2x3x4x** [comment]
I did not so I've quit trying for now because I have a job, however this is still pending for me.
I'll give it a go some time soon and test it out on Android and iOS.


The main difference that  I see from the list is that you use capacitor core 3.2.2 and I was still on 3.0.0.

**Comment by sultanmyrza** [comment]
no I tried today and also had your issue 

![Screen Shot 2021-09-03 at 5 49 56 PM](https://user-images.githubusercontent.com/12681781/131989173-c0e997bb-e1fb-4de9-bf82-fa4b3115404b.png)

but then I just deleted node_modules, and did npm i again, also F1 > reload windows on vscode or F1 > restart angular serve migh solve the problem but it's really annoying issue. but once you got it working it works both for ios and android

**Comment by 1x2x3x4x** [comment]
I did all you said and nothing. I have no idea how to fix it or what else to try.

![Captura](https://user-images.githubusercontent.com/5964014/131992141-cac052a4-a2e8-42d6-8731-f94b9893c9b1.PNG)

You just did `npm i https://github.com/digaus/community-capacitor-wifi.git#capacitor3`?

**Comment by 1x2x3x4x** [comment]
After changing"@capacitor-community/wifi": "git+https://github.com/digaus/community-capacitor-wifi.git#capacitor3", to     "@capacitor-community/wifi": "git+https://github.com/sultanmyrza/community-capacitor-wifi.git#capacitor3",
and doing again npm i it started to work. 


Don't even ask, I don't know what was wrong.

**Comment by 1x2x3x4x** [comment]
So, after finally getting the demo to work, I can tell that both connect/disconnect work on Android 10 (Miui and OxygenOS), I can connect to an iOT device throought the Access Point. 

Ill try to get the demo working on iOS because so far I wasn't able to make it work.
@sultanmyrza how did you get it working on iOS?

**Comment by sultanmyrza** [comment]
@1x2x3x4x greate 

for ios you need to add app.entitlement and also make some configuration on apple website
I wrote before here https://github.com/digaus/community-capacitor-wifi/issues/11#issuecomment-900960732

**Comment by sultanmyrza** [comment]
@digaus do you think we can propose this plugin as @capacitor-community/wifi plugin?
it's working on capacitor 2, 3 both ios, android and also MIT licence.

Look good enough to me to prose as community wifi plugin.

I can write readme.md on installing with example snippets etc at weekend or so

What do you think?

**Comment by digaus** [comment]
Yeah that would be the plan. Just did not have time yet to write readme.md etc ^^

**Comment by digaus** [comment]
> Hi again,
> 
> I've had the time to test this further. It works so far with _Android_, _10/11,_ Samsung tablet, _MIUI_ and _OxygenOS_, both `connect` and `disconnect`,
> 
> However it fails with iOS and I get this error:
> 
> > `[] NEHotspotConfiguration invalid WPA/WPA2 passphrase length.
> > ERROR MESSAGE:  {"errorMessage":"ERROR_CONNECTION_FAILED","message":"ERROR_CONNECTION_FAILED"}`
> 
> We can't use connect with an empty password under iOS?

How do you pass the empty password? It might be that and empty string does not work. However sending `null/undefined` or just using `connect({ssid: 'YourSSID'})` should work.

**Comment by 1x2x3x4x** [comment]
Thanks, I did try that but getting another error:


```
21-09-14 12:55:14.002222+0200 App[3453:2632058] [] Failed to send a 9 message to nehelper: <dictionary: 0x1eb3b5280> { count = 1, transaction: 0, voucher = 0x0, contents =
"XPCErrorDescription" => <string: 0x1eb3b53e8> { length = 18, contents = "Connection invalid" }

}

2021-09-14 12:55:14.002333+0200 App[3453:2632058] [] NEHotspotConfigurationHelper failed to communicate to helper server.
ERROR MESSAGE:  {"message":"ERROR_CONNECTION_FAILED","errorMessage":"ERROR_CONNECTION_FAILED"}
```

**Comment by digaus** [comment]
> Thanks, I did try that but getting another error:
> 
> ```
> 21-09-14 12:55:14.002222+0200 App[3453:2632058] [] Failed to send a 9 message to nehelper: <dictionary: 0x1eb3b5280> { count = 1, transaction: 0, voucher = 0x0, contents =
> "XPCErrorDescription" => <string: 0x1eb3b53e8> { length = 18, contents = "Connection invalid" }
> 
> }
> 
> 2021-09-14 12:55:14.002333+0200 App[3453:2632058] [] NEHotspotConfigurationHelper failed to communicate to helper server.
> ERROR MESSAGE:  {"message":"ERROR_CONNECTION_FAILED","errorMessage":"ERROR_CONNECTION_FAILED"}
> ```

Have you tried restarting the smartphone. There is an issue with iOS that it sometimes does not want to connect until you restart it.

**Comment by 1x2x3x4x** [comment]
I did not try that but I've found this: https://developer.apple.com/forums/thread/127834

My project only had the capability to access the `WiFi Information` so I added on **Xcode** the `Hotspot Configuration` and `Network Extensions`.

After adding the two it's working so far.

**Comment by sultanmyrza** [comment]
> I did not try that but I've found this: https://developer.apple.com/forums/thread/127834
> 
> My project only had the capability to access the `WiFi Information` so I added on **Xcode** the `Hotspot Configuration` and `Network Extensions`.

For ios I described before extra setup [here](https://github.com/digaus/community-capacitor-wifi/issues/11#issuecomment-900960732) hope this helpfull

**Comment by sdunnin** [comment]
> I did all you said and nothing. I have no idea how to fix it or what else to try.
> 
> ![Captura](https://user-images.githubusercontent.com/5964014/131992141-cac052a4-a2e8-42d6-8731-f94b9893c9b1.PNG)
> 
> You just did `npm i https://github.com/digaus/community-capacitor-wifi.git#capacitor3`?

Having the same issue trying to use the capacitor3 branch. It appears that typescript typing information is missing. When I compare 'capacitor3' with 'master' branch I noticed that the `dist` folder missing and that is where VS code takes you when using "Go to Definition" command. dist folder to me implies some sort of build of the wifi package but not sure how that is supposed to work

**Comment by sdunnin** [comment]
Found this discussion which confirmed my thought that plugin as it exists in that capacitor3 branch needs to be built
https://github.com/digaus/community-capacitor-wifi/issues/29

**Comment by sdunnin** [comment]
I ended up creating a fork of this repo doing an `npm run build` on the capacitor3 branch and including the dist folder to include the typings. Then in the package.json dependency I point to my updated repo and all works well. Will point back to this repo once master branch is updated.

**Comment by digaus** [comment]
https://github.com/digaus/community-capacitor-wifi/issues/37
