### ISSUE TITLE
When to use connect or connectPrefix methods

### ISSUE THREAD

**Issue by IgorSamer** [digaus/community-capacitor-wifi#24]
What are the differences/advantages between connect and connectPrefix methods?

**Comment by digaus** [comment]
@IgorSamer

`connectPrefix` allows you to connect to wifi networks which SSID is not know but where you know how its prefix.

This is generally used for IoT devices. I personally use it to connect to the wifi network of various Shellys.

![image](https://user-images.githubusercontent.com/15358538/130123702-3f1ce9a3-c932-47b1-af4a-26102139fb9b.png)

**Comment by IgorSamer** [comment]
Got it! But how will it work if there are multiple SSID's with the same prefix? As in your screenshot where there are several shelly1...

**Comment by digaus** [comment]
For iOS it will show the device with the strongest signal and for android you can select which network you want to connect to
