### ISSUE TITLE
[capasitor3] Cannot find type 'boolean' in scope

### ISSUE THREAD

**Issue by sultanmyrza** [digaus/community-capacitor-wifi#28]
Yesterday when I try to run on iOS I got this error `Cannot find type 'boolean' in scope`

![Screen Shot 2021-08-27 at 7 55 27 PM](https://user-images.githubusercontent.com/12681781/131201315-8d8ae269-1ec5-4da2-b101-7743ca9915f9.png)

And made small change https://github.com/digaus/community-capacitor-wifi/pull/27

**Comment by sultanmyrza** [comment]
@digaus By the way when I clone your project to local machine in `ios` directory there was no `ios/Plugin.xcworkspace`

I come to this after googling https://github.com/ionic-team/capacitor/issues/668#issuecomment-411022083 .
also official docs claims this https://capacitorjs.com/docs/plugins/ios#getting-started
>To get started, first generate a plugin as shown in the Getting Started section of the Plugin guide.
Next, open `echo/ios/Plugin.xcworkspace` in Xcode. You then want to navigate to the .swift file for your plugin.

So I just run `cd ios && pod install`
then it generated `ios/Plugin.xcworkspace` and I was able to change code `boolean` to `Bool`

But it also generated these files which I didn't commint. @digaus  Should I commit them as well?
![Screen Shot 2021-08-28 at 9 16 52 AM](https://user-images.githubusercontent.com/12681781/131201622-fef371fb-d2c9-4b9a-bd02-6414ee4c520c.png)

**Comment by sultanmyrza** [comment]
Just side note maybe others find it helpfull.

I check other capacitor community plugin https://github.com/capacitor-community/bluetooth-le/tree/main/ios (works for ionic 2, 3) and they keep `Plugin.xcworkspace` in git

according to this [.gitignore](https://github.com/github/gitignore/blob/master/Swift.gitignore) seems reliable
```
## User settings
xcuserdata/
```

Also found this https://www.toptal.com/developers/gitignore where you can type you project + programming language and it generates .gitignore accordingly.
![Screen Shot 2021-08-28 at 10 15 56 AM](https://user-images.githubusercontent.com/12681781/131203101-0e29eb7e-c16f-4bf7-a203-8809c6755517.png)

**Comment by digaus** [comment]
https://github.com/digaus/community-capacitor-wifi/pull/27
