### ISSUE TITLE
Android Studio error  AppCompatActivity

### ISSUE THREAD

**Issue by Frtrillo** [digaus/community-capacitor-wifi#29]
error: cannot access AppCompatActivity
        this.wifiManager = (WifiManager) this.bridge.getActivity().getApplicationContext().getSystemService(Context.WIFI_SERVICE);
                                                                ^
  class file for androidx.appcompat.app.AppCompatActivity not found

Im trying to build the project but I get that error, on ionic 5 and angular 12

EDIT:
Looks like its because Im using Capacitor 3. I've tried this post: https://github.com/digaus/community-capacitor-wifi/issues/23

But cant install the #capacitor3 branch. When I do  npm i https://github.com/digaus/community-capacitor-wifi#capacitor3  , angular can't find the WiFi Import:
![image](https://user-images.githubusercontent.com/72965099/139492812-e5bd319c-0bf1-476e-8979-d251c843a0e4.png)
even tho it is on my dependencies package.json

    "@capacitor-community/wifi": "git+https://github.com/digaus/community-capacitor-wifi.git#capacitor3",

Thanks for the plugin,
Regards

**Comment by digaus** [comment]
Try clone it and build it yourself. Then install the folder.

Have not yet found the time to release a version. Will try to check out later.

**Comment by Frtrillo** [comment]
> Try clone it and build it yourself. Then install the folder.
> 
> Have not yet found the time to release a version. Will try to check out later.

Hi, Ive tried doing it like that installing it as a folder: " npm i .\community-capacitor-wifi-capacitor3\" 
But Im getting same issue, "cant find "@capacitor-community/wifi""
Packagejson:    "@capacitor-community/wifi": "file:community-capacitor-wifi-capacitor3",

**Comment by digaus** [comment]
> > Try clone it and build it yourself. Then install the folder.
> > Have not yet found the time to release a version. Will try to check out later.
> 
> Hi, Ive tried doing it like that installing it as a folder: " npm i .\community-capacitor-wifi-capacitor3" But Im getting same issue, "cant find "@capacitor-community/wifi"" Packagejson: "@capacitor-community/wifi": "file:community-capacitor-wifi-capacitor3",

Can you find it under node_modules/@capacitor-community/wifi ?

**Comment by Frtrillo** [comment]
> > > Try clone it and build it yourself. Then install the folder.
> > > Have not yet found the time to release a version. Will try to check out later.
> > 
> > 
> > Hi, Ive tried doing it like that installing it as a folder: " npm i .\community-capacitor-wifi-capacitor3" But Im getting same issue, "cant find "@capacitor-community/wifi"" Packagejson: "@capacitor-community/wifi": "file:community-capacitor-wifi-capacitor3",
> 
> Can you find it under `node_modules/@capacitor-community/wifi` ?

Yeah it is though:
![image](https://user-images.githubusercontent.com/72965099/139537528-c2ec7747-1031-4a5d-87fc-83332ce23f4e.png)
![image](https://user-images.githubusercontent.com/72965099/139537571-94547f02-b5e2-44cc-87ec-3432033dd7f4.png)

**Comment by digaus** [comment]
You have to run `npm run build` first on the plugin

**Comment by Frtrillo** [comment]
> You have to run `npm run build` first on the plugin

Alright that have worked me as a workaround as it wont work automatically with "npm i" on other computers because of the local nature. Maybe pushing the capacitor 3 branch to master? Worked fine so far on android 11

**Comment by Frtrillo** [comment]
> You have to run `npm run build` first on the plugin

Sorry to bother you again but why/how can I make it to work on remote the capacitor3 branch? I've tried to fork your repo and made capacitor3 as default branch but still wont' work , only way it works is downloading and running npm build, but I can't do that for remote deploys like i.e vercel
