### ISSUE TITLE
getSSID returns null on iOS 13+

### ISSUE THREAD

**Issue by Frtrillo** [digaus/community-capacitor-wifi#34]
First you have to allow access to location on info.plist: 

    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Application requires user’s location for better user experience.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Application requires user’s location for better user experience.</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Application requires user’s location for better user experience.</string>

But now when using Wifi.getSSID(), it returns null(works on android 12):

To Native ->  Wifi getSSID 129739871
2022-03-25 12:31:30.979775+0100 App[708:105867] [] nehelper sent invalid result code [1] for Wi-Fi information request
ERROR MESSAGE:  {"errorMessage":"ERROR_WIFI_INFORMATION_EMPTY","message":"ERROR_WIFI_INFORMATION_EMPTY"}
⚡️  [error] - {"errorMessage":"ERROR_WIFI_INFORMATION_EMPTY","message":"ERROR_WIFI_INFORMATION_EMPTY"}
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: ERROR_WIFI_INFORMATION_EMPTY
pe@capacitor://localhost/main.ffac96e728e77f73.js:1:515225

**Comment by digaus** [comment]
Have you check here? https://github.com/digaus/community-capacitor-wifi/issues/11#issuecomment-900960732

> finally add these in App.entitlements
> ```
> 
> <dict>
>     <key>com.apple.developer.networking.HotspotConfiguration</key>
>     <true/>
>     <key>com.apple.developer.networking.networkextension</key>
>     <array>
> 	    <string>app-proxy-provider</string>
>     </array>
>     <key>com.apple.external-accessory.wireless-configuration</key>
>     <true/>
>     <key>com.apple.developer.networking.wifi-info</key>
>     <true/>
> </dict>
> ```
