### ISSUE TITLE
disconnect() results in ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by tylerclark** [digaus/community-capacitor-wifi#35]
Not sure what I am doing wrong but I want simply call:
```
Wifi.disconnect();
```

And I get back:
```
{"message":"ERROR_NOT_SUPPORTED","errorMessage":"ERROR_NOT_SUPPORTED"}
```

Anybody know what I'm doing wrong?

--
Running iOS 15.4.1, Ionic 6, Capacitor 3

**Comment by digaus** [comment]
`disconnect` is currently no implemented on iOS. When I am going to implement it you also could only disconnect from networks which you added with the your app.

**Comment by tylerclark** [comment]
Yes that would be perfect. Right now we want to use it similar to how GoPro devices you can connect and download files and then disconnect so the disconnect feature is very important. I saw there was some code in there but it was commented out. I tried to uncomment and get working but I kept getting the error `extra trailing closure passed in call` and wasn't sure how to resolve. If you can implement the `disconnect` method that would be amazing!

**Comment by digaus** [comment]
https://github.com/digaus/community-capacitor-wifi/commit/3fc1395043591824c4d319c04c0dbb9b9431492f

Added disconnect. Tested on iPhone 12 mini

**Comment by tylerclark** [comment]
Brilliant! Thank you! Will this extension work with Capacitor 3? I was using [this fork](https://github.com/numbersprotocol/community-capacitor-wifi#capacitor3) as it said it worked with cap 3.

**Comment by tylerclark** [comment]
Hello there, I have been trying to get disconnect to work for quite a while now but I get `ERROR_NOT_SUPPORTED` even though I have iOS 15.5. Shouldn't my phone be able to support and disconnect from the same network it was able to join? This is what I have in my `package.json` file:
```
"@capacitor-community/wifi": "git+https://github.com/digaus/community-capacitor-wifi.git#capacitor3",
```
Is that correct? Maybe I'm just referencing this code incorrectly?

Also: Is it possible to update the [npm package](https://www.npmjs.com/package/capacitor-wifi)? Maybe that would resolve my issues?

Update: looking at this code I set some debug statements and I see it hits line 2, then line 10, then like 4. When I disable line 10 things seem to work fine. I believe this could be a race condition?

```
1    @objc func disconnect(_ call: CAPPluginCall) {
2       if #available(iOS 11, *) {
3            DispatchQueue.main.async {
4                self.wifiHandler = WifiHandler(call: call, disconnect: true)
5            }
6
7        } else {
8            call.reject("ERROR_ONLY_SUPPORTED_IOS_11")
9        }
10        call.reject("ERROR_NOT_SUPPORTED")
11    }
```

**Comment by sultanmyrza** [comment]
@tylerclark, can you try `npm install 'digaus/community-capacitor-wifi#capacitor3'`?

**Comment by sultanmyrza** [comment]
> Hello there, I have been trying to get disconnect to work for quite a while now but I get `ERROR_NOT_SUPPORTED` even though I have iOS 15.5. Shouldn't my phone be able to support and disconnect from the same network it was able to join? This is what I have in my `package.json` file:
> 
> ```
> "@capacitor-community/wifi": "git+https://github.com/digaus/community-capacitor-wifi.git#capacitor3",
> ```
> 
> Is that correct? Maybe I'm just referencing this code incorrectly?
> 
> Also: Is it possible to update the [npm package](https://www.npmjs.com/package/capacitor-wifi)? Maybe that would resolve my issues?
> 
> Update: looking at this code I set some debug statements and I see it hits line 2, then line 10, then like 4. When I disable line 10 things seem to work fine. I believe this could be a race condition?
> 
> ```
> 1    @objc func disconnect(_ call: CAPPluginCall) {
> 2       if #available(iOS 11, *) {
> 3            DispatchQueue.main.async {
> 4                self.wifiHandler = WifiHandler(call: call, disconnect: true)
> 5            }
> 6
> 7        } else {
> 8            call.reject("ERROR_ONLY_SUPPORTED_IOS_11")
> 9        }
> 10        call.reject("ERROR_NOT_SUPPORTED")
> 11    }
> ```

@tylerclark, can you try `npm install 'digaus/community-capacitor-wifi#capacitor3'`?

**Comment by tylerclark** [comment]
That too works. But it still doesn't remove the race condition. If you run this code in Xcode line `10` will run before line `4` and therefore never disconnect.

**Comment by sultanmyrza** [comment]
> That too works. But it still doesn't remove the race condition. If you run this code in Xcode line `10` will run before line `4` and therefore never disconnect.

I believe `DispatchQueue.main.async` is like `new Promise(()=>{})` in javascript that's why line 10 comes before line 4

@tylerclark what if you remove line 10? I'm not sure but `call.reject("ERROR_NOT_SUPPORTED")` seems extra. Need to ask @digaus why line 10 is needed?

**Comment by tylerclark** [comment]
With line 10 removed everything works fine. Which is what I did and I forked the repo purely for that, but I was not able to get my forked repo to install properly using Ionic AppFlow. Probably another issue but yeah!

**Comment by sultanmyrza** [comment]
> With line 10 removed everything works fine. Which is what I did and I forked the repo purely for that, but I was not able to get my forked repo to install properly using Ionic AppFlow. Probably another issue but yeah!

@tylerclark can you share your fork? want to check `package.json`

**Comment by tylerclark** [comment]
https://github.com/tylerclark/community-capacitor-wifi

**Comment by sultanmyrza** [comment]
> https://github.com/tylerclark/community-capacitor-wifi

@tylerclark Installing from git didn't work that's why I added this [line](https://github.com/tylerclark/community-capacitor-wifi/blob/ffe4b89c46184a282cfe5919923ef4fb76b02020/package.json#L28). But I'm not sure how AppFlow works.

**Comment by tylerclark** [comment]
Yeah I guess I don't know how AppFlow works either. It runs everything in the cloud. I see it run `npm ci --quiet --no-optional` and then `npm run build`. What does that line do? How can I get it to run `npm run prepare`? Maybe a post package.json capability?

**Comment by sultanmyrza** [comment]
> Yeah I guess I don't know how AppFlow works either. It runs everything in the cloud. I see it run `npm ci --quiet --no-optional` and then `npm run build`. What does that line do? How can I get it to run `npm run prepare`? Maybe a post package.json capability?

@tylerclark I hope [this](https://stackoverflow.com/a/61975270/6133329) can explaing more or less why `npm run prepare` was needed. 

I think the better solution will be to merge your pull request and install from npm registry. For that please ask @digaus to merge your PR.

**Comment by digaus** [comment]
Merged now. Was my bad sorry guys ^^

**Comment by tylerclark** [comment]
@sultanmyrza How do I pull from npm registry? @digaus thanks for merging. Is it possible to put in npm? I'm not sure what is up with AppFlow but I still get "ERROR_NOT_SUPPORTED" after pointing to my repo and this one. So it's clearly caching the wrong plugin. When I run locally on Xcode it works!
